// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSiUJhC72SMEI6TCW3l7G6o1jpk7Aluyo',
    appId: '1:502098353600:web:f15886a3edb08783eefc25',
    messagingSenderId: '502098353600',
    projectId: 'chat-demo-648c2',
    authDomain: 'chat-demo-648c2.firebaseapp.com',
    storageBucket: 'chat-demo-648c2.appspot.com',
    measurementId: 'G-H6X00VSTQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrakUMAbxysQiEMrlg2h3dmCUzsUSyoMw',
    appId: '1:502098353600:android:5e433d8a6c658706eefc25',
    messagingSenderId: '502098353600',
    projectId: 'chat-demo-648c2',
    storageBucket: 'chat-demo-648c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-gUooQ047SnvyU9Zp1huII8DZy9QEYnI',
    appId: '1:502098353600:ios:25c359040bf56a29eefc25',
    messagingSenderId: '502098353600',
    projectId: 'chat-demo-648c2',
    storageBucket: 'chat-demo-648c2.appspot.com',
    iosBundleId: 'com.rnw.chatdemo.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-gUooQ047SnvyU9Zp1huII8DZy9QEYnI',
    appId: '1:502098353600:ios:6ebe908fa3658997eefc25',
    messagingSenderId: '502098353600',
    projectId: 'chat-demo-648c2',
    storageBucket: 'chat-demo-648c2.appspot.com',
    iosBundleId: 'com.rnw.chatdemo.chatapp.RunnerTests',
  );
}
